use std::collections::HashMap;
use std::sync::{Arc, Mutex};
use std::time::{Duration, Instant};
use serde::{Deserialize, Serialize};
use tokio::sync::mpsc;
use crate::db::{slot_repo, metrics_repo, learning_repo, memory_repo, trust_repo};
use crate::services::loop_launcher::{self, LoopConfig};
use crate::services::process_runner::ProcessRunner;
use crate::services::{learning_engine, event_bus};

// ── Types ──

/// Describes the health status of an agent in a slot
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct AgentHealth {
    pub slot_id: String,
    pub process_id: Option<String>,
    pub agent_type: String,
    pub status: String,
    pub progress_pct: Option<f64>,
    pub current_task: Option<String>,
    pub last_output_at: Option<String>,
    pub failover_attempts: u32,
}

/// An alert generated by health monitoring
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct HealthAlert {
    pub slot_id: String,
    pub alert_type: String, // "non_responsive", "repeated_output", "unexpected_exit", "stall", "rate_limit"
    pub message: String,
    pub actions: Vec<String>, // "wait", "restart", "reassign", "abort"
    pub created_at: String,
}

/// Status parsed from .crossroads/status.json
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct AgentStatus {
    pub progress_pct: Option<f64>,
    pub current_task: Option<String>,
    pub status: Option<String>, // "running", "completed", "failed"
    pub error: Option<String>,
    pub updated_at: Option<String>,
}

/// Spawn request configuration
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct SpawnRequest {
    pub slot_id: String,
    pub session_id: String,
    pub slot_index: u32,
    pub agent_type: String,
    pub worktree_path: String,
    pub prd_path: String,
    pub branch_name: String,
    pub max_iterations: Option<u32>,
    pub sleep_seconds: Option<u32>,
    pub skill_content: Option<String>,
    pub handoff_context: Option<String>,
}

/// Failover order for agent types
const FAILOVER_ORDER: &[&str] = &["claude", "gemini", "codex"];

// ── Tracked agent state ──

#[derive(Debug)]
struct TrackedAgent {
    slot_id: String,
    process_id: String,
    agent_type: String,
    worktree_path: String,
    spawn_request: SpawnRequest,
    started_at: Instant,
    last_output_at: Instant,
    last_output_text: String,
    repeated_count: u32,
    failover_attempts: u32,
    status_last_modified: Option<String>,
}

// ── Agent Lifecycle Manager ──

pub struct AgentLifecycleManager {
    process_runner: Arc<ProcessRunner>,
    agents: Arc<Mutex<HashMap<String, TrackedAgent>>>, // slot_id -> TrackedAgent
    alert_tx: mpsc::UnboundedSender<HealthAlert>,
    event_tx: mpsc::UnboundedSender<LifecycleEvent>,
}

/// Events emitted by lifecycle manager (consumed by Tauri event emitter)
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct LifecycleEvent {
    pub event_type: String, // "status_change", "health_alert", "agent_output", "metrics_update"
    pub slot_id: String,
    pub payload: serde_json::Value,
}

impl AgentLifecycleManager {
    pub fn new(
        alert_tx: mpsc::UnboundedSender<HealthAlert>,
        event_tx: mpsc::UnboundedSender<LifecycleEvent>,
    ) -> Self {
        Self {
            process_runner: Arc::new(ProcessRunner::new()),
            agents: Arc::new(Mutex::new(HashMap::new())),
            alert_tx,
            event_tx,
        }
    }

    // ── US-001: Agent Spawner ──

    /// Spawn an agent in a slot. Transitions slot: empty → provisioning → running.
    pub fn spawn_agent(&self, req: SpawnRequest) -> Result<String, String> {
        // 1. Resolve loop script
        let script = loop_launcher::resolve_loop_script(&req.agent_type)?;

        // 2. Generate AGENT.md context
        let config = LoopConfig {
            agent_type: req.agent_type.clone(),
            worktree_path: req.worktree_path.clone(),
            prd_path: req.prd_path.clone(),
            max_iterations: req.max_iterations.unwrap_or(10),
            sleep_seconds: req.sleep_seconds.unwrap_or(10),
            session_id: req.session_id.clone(),
            slot_index: req.slot_index,
            skill_content: req.skill_content.clone(),
            handoff_context: req.handoff_context.clone(),
            chairman_brief: None,
            task_description: None,
        };
        let ctx = loop_launcher::generate_agent_md(&config)?;

        // 3. Update slot to provisioning
        slot_repo::update_slot(&req.slot_id, "provisioning", Some("Preparing agent..."))
            .map_err(|e| e.to_string())?;
        self.emit_status_change(&req.slot_id, "provisioning");

        // 4. Ensure metrics row exists
        metrics_repo::get_or_create(&req.slot_id).map_err(|e| e.to_string())?;

        // 5. Build env and args
        let env = loop_launcher::build_env(&config, &ctx);
        let args = loop_launcher::build_args(&config);

        // 6. Spawn via ProcessRunner with output capture
        let slot_id_for_output = req.slot_id.clone();
        let agents_ref = self.agents.clone();
        let alert_tx = self.alert_tx.clone();
        let event_tx = self.event_tx.clone();

        let arg_refs: Vec<&str> = args.iter().map(|s| s.as_str()).collect();
        let process_id = self.process_runner.spawn(
            &script,
            &arg_refs,
            Some(&req.worktree_path),
            Some(env),
            move |pid, text| {
                // Update last_output tracking for health monitoring
                let mut agents = agents_ref.lock().unwrap();
                if let Some(agent) = agents.get_mut(&slot_id_for_output) {
                    // Detect repeated output
                    if text.trim() == agent.last_output_text.trim() && !text.trim().is_empty() {
                        agent.repeated_count += 1;
                        if agent.repeated_count >= 5 {
                            let _ = alert_tx.send(HealthAlert {
                                slot_id: slot_id_for_output.clone(),
                                alert_type: "repeated_output".into(),
                                message: format!("Agent produced identical output {} times", agent.repeated_count),
                                actions: vec!["wait".into(), "restart".into(), "reassign".into(), "abort".into()],
                                created_at: chrono::Utc::now().to_rfc3339(),
                            });
                        }
                    } else {
                        agent.repeated_count = 0;
                        agent.last_output_text = text.to_string();
                    }
                    agent.last_output_at = Instant::now();

                    // Detect rate limit errors (US-003)
                    let lower = text.to_lowercase();
                    if lower.contains("rate limit") || lower.contains("429") || lower.contains("too many requests") {
                        let _ = alert_tx.send(HealthAlert {
                            slot_id: slot_id_for_output.clone(),
                            alert_type: "rate_limit".into(),
                            message: "Rate limit detected in agent output".into(),
                            actions: vec!["wait".into(), "reassign".into(), "abort".into()],
                            created_at: chrono::Utc::now().to_rfc3339(),
                        });
                    }
                }

                // WIRING 5: Check for dangerous operations in PTY output
                let dangerous = crate::services::safe_executor::detect_dangerous_ops(text);
                if !dangerous.is_empty() {
                    let risk = crate::services::safe_executor::highest_risk(&dangerous);
                    let decision = crate::services::safe_executor::evaluate_policy(risk, &[], &dangerous[0].pattern);
                    if decision == crate::services::safe_executor::PolicyDecision::RequireHumanApproval {
                        let _ = crate::services::safe_executor::trigger_gate(&slot_id_for_output, &dangerous[0], None);
                    }
                }

                // Emit output event
                let _ = event_tx.send(LifecycleEvent {
                    event_type: "agent_output".into(),
                    slot_id: slot_id_for_output.clone(),
                    payload: serde_json::json!({ "processId": pid, "text": text }),
                });
            },
        )?;

        // 7. Track the agent
        {
            let mut agents = self.agents.lock().unwrap();
            agents.insert(req.slot_id.clone(), TrackedAgent {
                slot_id: req.slot_id.clone(),
                process_id: process_id.clone(),
                agent_type: req.agent_type.clone(),
                worktree_path: req.worktree_path.clone(),
                spawn_request: req.clone(),
                started_at: Instant::now(),
                last_output_at: Instant::now(),
                last_output_text: String::new(),
                repeated_count: 0,
                failover_attempts: 0,
                status_last_modified: None,
            });
        }

        // 8. Update slot to running
        slot_repo::update_slot(&req.slot_id, "running", Some("Agent started"))
            .map_err(|e| e.to_string())?;
        self.emit_status_change(&req.slot_id, "running");

        Ok(process_id)
    }

    /// Abort an agent in a slot
    pub fn abort_agent(&self, slot_id: &str) -> Result<(), String> {
        let process_id = {
            let agents = self.agents.lock().unwrap();
            agents.get(slot_id)
                .map(|a| a.process_id.clone())
                .ok_or_else(|| format!("No active agent in slot {}", slot_id))?
        };

        self.process_runner.kill(&process_id)?;

        {
            let mut agents = self.agents.lock().unwrap();
            agents.remove(slot_id);
        }

        slot_repo::update_slot(slot_id, "error", Some("Aborted by user"))
            .map_err(|e| e.to_string())?;
        self.emit_status_change(slot_id, "error");

        Ok(())
    }

    /// Get health status for a slot
    pub fn get_health(&self, slot_id: &str) -> Option<AgentHealth> {
        let agents = self.agents.lock().unwrap();
        agents.get(slot_id).map(|a| {
            let last_out = chrono::Utc::now() - chrono::Duration::from_std(a.last_output_at.elapsed()).unwrap_or_default();
            AgentHealth {
                slot_id: a.slot_id.clone(),
                process_id: Some(a.process_id.clone()),
                agent_type: a.agent_type.clone(),
                status: "running".into(),
                progress_pct: None,
                current_task: None,
                last_output_at: Some(last_out.to_rfc3339()),
                failover_attempts: a.failover_attempts,
            }
        })
    }

    /// Get health status for all active agents
    pub fn get_all_health(&self) -> Vec<AgentHealth> {
        let agents = self.agents.lock().unwrap();
        agents.values().map(|a| {
            let last_out = chrono::Utc::now() - chrono::Duration::from_std(a.last_output_at.elapsed()).unwrap_or_default();
            AgentHealth {
                slot_id: a.slot_id.clone(),
                process_id: Some(a.process_id.clone()),
                agent_type: a.agent_type.clone(),
                status: "running".into(),
                progress_pct: None,
                current_task: None,
                last_output_at: Some(last_out.to_rfc3339()),
                failover_attempts: a.failover_attempts,
            }
        }).collect()
    }

    // ── US-002: Status Polling ──

    /// Poll status.json for a given slot. Called by the monitoring loop.
    /// Returns parsed status and emits events on changes.
    pub fn poll_status(&self, slot_id: &str) -> Option<AgentStatus> {
        let worktree_path = {
            let agents = self.agents.lock().unwrap();
            agents.get(slot_id)?.worktree_path.clone()
        };

        let status_path = std::path::Path::new(&worktree_path)
            .join(".crossroads")
            .join("status.json");

        let content = std::fs::read_to_string(&status_path).ok()?;
        let status: AgentStatus = serde_json::from_str(&content).ok()?;

        // Check for completion
        if status.status.as_deref() == Some("completed") {
            self.handle_completion(slot_id);
        } else if status.status.as_deref() == Some("failed") {
            self.handle_failure(slot_id, status.error.as_deref().unwrap_or("Unknown error"));
        }

        // Check for stall (status.json not modified in >5 minutes)
        if let Some(ref updated) = status.updated_at {
            let mut agents = self.agents.lock().unwrap();
            if let Some(agent) = agents.get_mut(slot_id) {
                let changed = agent.status_last_modified.as_deref() != Some(updated);
                if changed {
                    agent.status_last_modified = Some(updated.clone());
                } else {
                    // Same timestamp — check if stalling
                    if agent.last_output_at.elapsed() > Duration::from_secs(300) {
                        let _ = self.alert_tx.send(HealthAlert {
                            slot_id: slot_id.to_string(),
                            alert_type: "stall".into(),
                            message: "Agent status unchanged for >5 minutes".into(),
                            actions: vec!["wait".into(), "restart".into(), "reassign".into(), "abort".into()],
                            created_at: chrono::Utc::now().to_rfc3339(),
                        });
                    }
                }
            }
        }

        // Update slot's current_task in DB if changed
        if let Some(ref task) = status.current_task {
            let _ = slot_repo::update_slot(slot_id, "running", Some(task));
        }

        // Emit health event
        let _ = self.event_tx.send(LifecycleEvent {
            event_type: "status_poll".into(),
            slot_id: slot_id.to_string(),
            payload: serde_json::to_value(&status).unwrap_or_default(),
        });

        Some(status)
    }

    // ── US-003: Failover ──

    /// Attempt failover to next agent type after rate limit or failure
    pub fn failover(&self, slot_id: &str) -> Result<String, String> {
        let (current_type, mut req, attempts) = {
            let mut agents = self.agents.lock().unwrap();
            let agent = agents.get_mut(slot_id)
                .ok_or_else(|| format!("No active agent in slot {}", slot_id))?;
            agent.failover_attempts += 1;
            (agent.agent_type.clone(), agent.spawn_request.clone(), agent.failover_attempts)
        };

        // Kill current process
        self.abort_agent(slot_id).ok(); // ignore error if already dead

        // Exponential backoff: 2^attempts seconds, max 60s
        let delay_secs = std::cmp::min(2u64.pow(attempts), 60);
        std::thread::sleep(Duration::from_secs(delay_secs));

        // Rotate to next agent type
        let next_type = next_agent_type(&current_type);

        // Record failover in metrics
        metrics_repo::record_failover(slot_id).map_err(|e| e.to_string())?;

        // Update request and respawn
        req.agent_type = next_type.to_string();
        self.spawn_agent(req)
    }

    // ── US-004: Health Checks ──

    /// Run health checks on all active agents. Called periodically.
    pub fn check_health(&self) {
        let slot_ids: Vec<String> = {
            let agents = self.agents.lock().unwrap();
            agents.keys().cloned().collect()
        };

        for slot_id in slot_ids {
            let agents = self.agents.lock().unwrap();
            if let Some(agent) = agents.get(&slot_id) {
                // Non-responsive check (>2 minutes no output)
                if agent.last_output_at.elapsed() > Duration::from_secs(120) {
                    let _ = self.alert_tx.send(HealthAlert {
                        slot_id: slot_id.clone(),
                        alert_type: "non_responsive".into(),
                        message: "Agent has not produced output for >2 minutes".into(),
                        actions: vec!["wait".into(), "restart".into(), "reassign".into(), "abort".into()],
                        created_at: chrono::Utc::now().to_rfc3339(),
                    });
                }
            }
            drop(agents);

            // Check process still alive
            let process_id = {
                let agents = self.agents.lock().unwrap();
                agents.get(&slot_id).map(|a| a.process_id.clone())
            };
            if let Some(pid) = process_id {
                let active = self.process_runner.list_active();
                if !active.contains(&pid) {
                    // Process died unexpectedly
                    let _ = self.alert_tx.send(HealthAlert {
                        slot_id: slot_id.clone(),
                        alert_type: "unexpected_exit".into(),
                        message: "Agent process exited unexpectedly".into(),
                        actions: vec!["restart".into(), "reassign".into(), "abort".into()],
                        created_at: chrono::Utc::now().to_rfc3339(),
                    });
                }
            }

            // Poll status.json
            self.poll_status(&slot_id);
        }
    }

    /// Handle an alert action from the user
    pub fn handle_alert_action(&self, slot_id: &str, action: &str) -> Result<(), String> {
        match action {
            "wait" => {
                // Snooze — just reset the last_output_at to delay next alert
                let mut agents = self.agents.lock().unwrap();
                if let Some(agent) = agents.get_mut(slot_id) {
                    agent.last_output_at = Instant::now();
                }
                Ok(())
            }
            "restart" => {
                let req = {
                    let agents = self.agents.lock().unwrap();
                    agents.get(slot_id)
                        .map(|a| a.spawn_request.clone())
                        .ok_or_else(|| "No agent to restart".to_string())?
                };
                self.abort_agent(slot_id).ok();
                self.spawn_agent(req)?;
                Ok(())
            }
            "reassign" => {
                self.failover(slot_id)?;
                Ok(())
            }
            "abort" => {
                self.abort_agent(slot_id)
            }
            _ => Err(format!("Unknown action: {}", action)),
        }
    }

    // ── Internal helpers ──

    fn handle_completion(&self, slot_id: &str) {
        // Update slot to done
        let _ = slot_repo::update_slot(slot_id, "done", Some("Completed"));
        self.emit_status_change(slot_id, "done");

        // Gather info from tracked agent before removing
        let (elapsed_ms, session_id, agent_type, task_desc) = {
            let agents = self.agents.lock().unwrap();
            let elapsed = agents.get(slot_id).map(|a| a.started_at.elapsed().as_millis() as i64).unwrap_or(0);
            let sid = agents.get(slot_id).map(|a| a.spawn_request.session_id.clone());
            let atype = agents.get(slot_id).map(|a| a.agent_type.clone()).unwrap_or_default();
            let task = agents.get(slot_id).map(|a| a.spawn_request.handoff_context.clone().unwrap_or_default()).unwrap_or_default();
            (elapsed, sid, atype, task)
        };

        // Record metrics
        let _ = metrics_repo::record_story_completed(slot_id, elapsed_ms);

        // Record LearningRecord for this slot's work
        if let Some(ref sid) = session_id {
            let story_title = task_desc.chars().take(100).collect::<String>();
            let domain = learning_engine::categorize_story(&story_title, &[]);

            let record = learning_repo::record_learning(
                sid,
                &format!("slot-{}", slot_id),
                &story_title,
                "medium", // complexity
                &agent_type,
                elapsed_ms,
                0, // cost_cents — will be filled by cost events
                0, 0, 0, // files/lines — not tracked at this level
                1, 1, // tests_run, tests_passed (success)
                0,     // conflicts
                true,  // success
                "[]",
            );

            if let Ok(ref lr) = record {
                // Update performance profile
                let _ = learning_repo::update_performance_profile(&agent_type, &domain, lr);

                event_bus::emit_log("info", "intelligence",
                    &format!("Learning recorded: {} completed by {} in {}ms", story_title, agent_type, elapsed_ms), None);
            }

            // Extract memories from all session learning records
            let records = learning_repo::fetch_learning_records(sid).unwrap_or_default();
            let extracted = memory_repo::auto_extract_memories(sid, &records).unwrap_or_default();
            if !extracted.is_empty() {
                event_bus::emit_log("info", "intelligence",
                    &format!("{} memories extracted from session", extracted.len()), None);
            }

            // Compute/update trust score for this agent+domain
            let _ = trust_repo::compute_trust(&agent_type, &domain);
        }

        // Remove from tracked agents
        let mut agents = self.agents.lock().unwrap();
        agents.remove(slot_id);
    }

    fn handle_failure(&self, slot_id: &str, error: &str) {
        let _ = slot_repo::update_slot(slot_id, "error", Some(error));
        self.emit_status_change(slot_id, "error");
        let _ = metrics_repo::record_story_failed(slot_id);

        // Record failure as LearningRecord
        let (elapsed_ms, session_id, agent_type, task_desc) = {
            let agents = self.agents.lock().unwrap();
            let elapsed = agents.get(slot_id).map(|a| a.started_at.elapsed().as_millis() as i64).unwrap_or(0);
            let sid = agents.get(slot_id).map(|a| a.spawn_request.session_id.clone());
            let atype = agents.get(slot_id).map(|a| a.agent_type.clone()).unwrap_or_default();
            let task = agents.get(slot_id).map(|a| a.spawn_request.handoff_context.clone().unwrap_or_default()).unwrap_or_default();
            (elapsed, sid, atype, task)
        };

        if let Some(ref sid) = session_id {
            let story_title = task_desc.chars().take(100).collect::<String>();
            let domain = learning_engine::categorize_story(&story_title, &[]);

            let record = learning_repo::record_learning(
                sid, &format!("slot-{}", slot_id), &story_title,
                "medium", &agent_type, elapsed_ms, 0,
                0, 0, 0, 1, 0, 0, false, "[]",
            );

            if let Ok(ref lr) = record {
                let _ = learning_repo::update_performance_profile(&agent_type, &domain, lr);
            }

            // Store failure as memory
            let _ = memory_repo::store_memory(
                &agent_type, &domain, "failure",
                &format!("Failed on '{}': {}", story_title, error),
                0.9, Some(sid), None, "[]",
            );

            let _ = trust_repo::compute_trust(&agent_type, &domain);

            event_bus::emit_log("warn", "intelligence",
                &format!("Failure recorded: {} by {} — {}", story_title, agent_type, error), None);
        }

        let mut agents = self.agents.lock().unwrap();
        agents.remove(slot_id);
    }

    fn emit_status_change(&self, slot_id: &str, status: &str) {
        let _ = self.event_tx.send(LifecycleEvent {
            event_type: "status_change".into(),
            slot_id: slot_id.to_string(),
            payload: serde_json::json!({ "status": status }),
        });
    }
}

/// Get the next agent type in failover order
fn next_agent_type(current: &str) -> &'static str {
    let idx = FAILOVER_ORDER.iter().position(|&t| t == current).unwrap_or(0);
    FAILOVER_ORDER[(idx + 1) % FAILOVER_ORDER.len()]
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_next_agent_type() {
        assert_eq!(next_agent_type("claude"), "gemini");
        assert_eq!(next_agent_type("gemini"), "codex");
        assert_eq!(next_agent_type("codex"), "claude");
        assert_eq!(next_agent_type("unknown"), "gemini"); // falls back to idx 0 → next is 1
    }

    #[test]
    fn test_health_alert_serialization() {
        let alert = HealthAlert {
            slot_id: "s1".into(),
            alert_type: "non_responsive".into(),
            message: "test".into(),
            actions: vec!["wait".into(), "restart".into()],
            created_at: "2026-03-29T12:00:00Z".into(),
        };
        let json = serde_json::to_string(&alert).unwrap();
        assert!(json.contains("nonResponsive") || json.contains("non_responsive"));
    }

    #[test]
    fn test_spawn_request_serialization() {
        let req = SpawnRequest {
            slot_id: "s1".into(),
            session_id: "sess1".into(),
            slot_index: 0,
            agent_type: "claude".into(),
            worktree_path: "/tmp/wt".into(),
            prd_path: "/tmp/prd.json".into(),
            branch_name: "feat/test".into(),
            max_iterations: Some(5),
            sleep_seconds: None,
            skill_content: None,
            handoff_context: None,
        };
        let json = serde_json::to_string(&req).unwrap();
        assert!(json.contains("slotId"));
        assert!(json.contains("sessionId"));
    }

    #[test]
    fn test_agent_status_parsing() {
        let json = r#"{"progressPct": 45.0, "currentTask": "Implementing US-002", "status": "running"}"#;
        let status: AgentStatus = serde_json::from_str(json).unwrap();
        assert_eq!(status.progress_pct, Some(45.0));
        assert_eq!(status.current_task, Some("Implementing US-002".into()));
        assert_eq!(status.status, Some("running".into()));
    }
}
